# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2.1
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:14-browsers

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      - run: xvfb-run -a npm run test -- --watch=false --browsers=ChromeHeadless

      # build
      - run: npm run build -- --base-href /PivotHelper/ --deploy-url /PivotHelper/ --prod

      # deploy
      - run: npx angular-cli-ghpages --dir=dist/PivotHelper --repo=https://GH_TOKEN@github.com/BjoernKW/PivotHelper.git --name="BjoernKW" --email=bjoern@bjoernkw.com

workflows:
  jobs:
    - build:
        filters:
          branches:
            only: master
